import "../../Styles/globals.scss";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import ClientLayout from "./ClientLayout";
import { languages } from "@/app/i18n/settings";
import { Footer } from "@/app/Components/Footer";
import { TopButton } from "@/app/TopButton";
import { pretendard } from "@/app/Styles/fonts";

export const metadata: Metadata = {
  title: `HCL's Space`,
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lang: lng }));
}

export default async function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  if (!languages.includes(lang)) {
    notFound();
  }

  return (
    <div className={`${pretendard.variable} ${pretendard.className}`}>
      <ClientLayout params={{ lang }}>
        {children}
        <TopButton />
        <Footer />
      </ClientLayout>
      <div id="modal-root" />
    </div>
  );
}
